[package]
name = "blocks"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
dotenvy.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
